name: imgcap
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - faiss-gpu=1.7.2
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pip
  - pip:
    - datasets
    - h5py==3.7.0
    - huggingface-hub
    - pandas==1.4.3
    - Pillow==9.2.0
    - pyarrow==9.0.0
    - pyparsing==3.0.9
    - PyYAML==6.0
    - tokenizers
    - tqdm
    - transformers
    - git+https://github.com/jmhessel/pycocoevalcap
    - git+https://github.com/openai/CLIP.git